### PR TITLE
buttons level-left

### PR DESCRIPTION
**Pull request by 1AnthonyFamosa**

### CODE REVIEW

**Comment by alexgurr** [comment]
Hi! Thanks for raising this PR. Please can you give some more information, including the problem you are solving and a before/after screenshot?

**Comment by 1AnthonyFamosa** [comment]
trying out proposing the faSun button-code before

Trying out the faSun button

**Comment by alexgurr** [comment]
This doesn't answer the question. I don't see the need to merge this in. Closing.

**Comment by alexgurr** [comment]
This doesn't answer the question. I don't see the need to merge this in. Closing.

**Pull request closed without merging**
